ci(changesets): versioning packages
FuelLabs/fuels-wallet pull request #1131
Opened 2024-03-13 15:36 UTC by fuel-service-user

This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases
## @fuel-wallet/connections@0.17.0

### Patch Changes

-   Updated dependencies \[]:
    -   @fuel-wallet/sdk@0.17.0
    -   @fuel-wallet/types@0.17.0

## @fuel-wallet/sdk@0.17.0

### Patch Changes

-   Updated dependencies \[]:
    -   @fuel-wallet/types@0.17.0

## @fuel-wallet/react@0.17.0

## @fuel-wallet/playwright-utils@0.17.0

## @fuel-wallet/types@0.17.0

## fuels-wallet@0.17.0

### Minor Changes

-   [#1123](https://github.com/FuelLabs/fuels-wallet/pull/1123) [`e18231a`](https://github.com/FuelLabs/fuels-wallet/commit/e18231abf779d11e468ecf57b5805bc646609bfe) Thanks [@bethatguyad](https://github.com/bethatguyad)! - perf: eliminating asset avatar flashing

### Patch Changes

-   Updated dependencies \[]:
    -   @fuel-wallet/connections@0.17.0
    -   @fuel-wallet/sdk@0.17.0
    -   @fuel-wallet/types@0.17.0

2024-03-13 15:45 UTC, helciofranco approved these changes

2024-03-13 16:56 UTC, luizstacio requested changes
lets hold this until we get the new updates of the package updates in.

2024-03-14 23:23 UTC, helciofranco approved these changes

2024-03-15 00:30 UTC, luizstacio approved these changes

2024-03-15 01:27 UTC, merged