feat(app): add network flow
FuelLabs/fuels-wallet pull request #120
Opened 2022-09-23 19:01 UTC by pedronauck

2022-09-27 14:11 UTC, luizstacio requested changes
- Try to split this PR into more small scopes
- When accessing the storybook some components are not working 
<img width="819" alt="Screen Shot 2022-09-27 at 11 08 32 AM" src="https://user-images.githubusercontent.com/3941923/192549907-6a54e745-e065-484f-9d94-9e0eaeb5ce74.png">
- When finishing creating a network it could go back home with the new network already selected.

2022-09-29 22:21 UTC, pedronauck commented on packages/app/package.json
> +    "storybook-addon-react-router-v6": "^0.2.1",
✅

2022-09-29 22:21 UTC, pedronauck commented on packages/app/cypress/e2e/FaucetDialog.cy.ts
> -    /** Checks empty balance */
✅

2022-09-29 22:21 UTC, pedronauck commented on packages/app/src/main.tsx
> +if (import.meta.env.DEBUG === "test") {
✅

2022-09-30 01:49 UTC, luizstacio requested changes

2022-09-30 01:49 UTC, luizstacio commented on packages/app/src/systems/Core/components/Layout/Layout.tsx
> +        {isPublic ? <>{children}</> : <Flex css={styles.wrapper}>{children}</Flex>}
Can we keep the rule for didn't change these cases? It's more readable with the `()`

2022-09-30 01:49 UTC, luizstacio commented on packages/app/src/systems/Core/components/Layout/Layout.tsx
> +      {import.meta.env.NODE_ENV === 'test' && (
This is just for cypress checking?

2022-09-30 01:49 UTC, luizstacio commented on packages/app/src/systems/SignUp/components/MnemonicRead/MnemonicRead.tsx
> +        <Button size="sm" color="gray" variant="ghost" css={{ width: 130 }} onPress={onCancel}>
Also, the old rule for formatting in multiple lines is better here.

2022-09-30 01:49 UTC, luizstacio commented on packages/app/src/systems/SignUp/components/MnemonicWrite/MnemonicWrite.test.tsx
> +const MNEMONIC = getPhraseFromValue(FuelMnemonic.generate(MNEMONIC_SIZE)) as string;
Also here the old rule for formatting was better, maybe the column number should be smaller

2022-09-30 01:49 UTC, luizstacio commented on packages/app/src/systems/SignUp/pages/CreateWallet/CreateWallet.tsx
> +          onCancel={() => navigate('/sign-up')}
Change this navigates to use the Pages.<route>()

2022-09-30 01:49 UTC, luizstacio commented on packages/app/src/systems/SignUp/pages/RecoverWallet/RecoverWallet.tsx
> +          onCancel={() => navigate('/sign-up')}
Also here: Pages.<route>() look for other places in this code

2022-09-30 01:55 UTC, luizstacio commented
Move the loader spinner to the other side of the network selector to prevent the selector from changing the page on after the loading state.
<img width="390" alt="Screen Shot 2022-09-29 at 10 54 13 PM" src="https://user-images.githubusercontent.com/3941923/193173305-712a2cc1-d8a5-4df1-b3a6-bd2678351a0f.png">

2022-09-30 18:45 UTC, luizstacio commented on .prettierrc
>          "printWidth": 100,
"printWidth": 80

2022-09-30 20:01 UTC, luizstacio approved these changes

2022-09-30 20:03 UTC, merged