feat: add auto update wallet
FuelLabs/fuels-wallet pull request #1243
Opened 2024-04-23 16:55 UTC by luizstacio

With this PR, the wallet will now check if it is running an old version and will auto-update once a new version is available on the background, respecting the user flow, if the users had any Wallet popup / tab open it will not update the wallet and delay it for more 15 minutes.

2024-04-23 19:25 UTC, arthurgeron submitted a review, later dismissed

2024-04-23 22:21 UTC, LuizAsFight requested changes

2024-04-23 22:21 UTC, LuizAsFight commented on packages/app/env.d.ts
> +    readonly VITE_API_VERSION: string;
```suggestion
    readonly VITE_CRX_VERSION_API: string;
```

2024-04-23 22:21 UTC, LuizAsFight commented on packages/app/env.d.ts
> +    readonly VITE_API_VERSION: string;
or remove it?

2024-04-24 21:41 UTC, LuizAsFight approved these changes

2024-04-24 21:41 UTC, merged