fix: vault crash on export seed auth fail
FuelLabs/fuels-wallet pull request #1279
Opened 2024-05-06 21:16 UTC by arthurgeron

Fixes soft-locked state after wrong password in `View Seed Phrase` screen

2024-05-06 21:27 UTC, luizstacio requested changes

2024-05-06 21:27 UTC, luizstacio commented on packages/app/src/systems/Settings/hooks/useExportVault.tsx
> +      });
We should not access the vault directly on the UI components. We should move the logic to get vaults method.

2024-05-23 08:43 UTC, HoTandy approved these changes
Apologies for the late review but looks good!!

2024-05-27 19:26 UTC, LuizAsFight approved these changes

2024-05-27 19:37 UTC, merged