feat: add an option to send custom gas limit when making transfers
FuelLabs/fuels-wallet pull request #1318
Opened 2024-05-28 19:08 UTC by helciofranco

- Add custom gas limit input when sending transfers
- Upgrade `fuels` to latest
- Improve UX when typing tip and gas limit

| 📷  Demo |
| --- |
| <video src="https://github.com/FuelLabs/fuels-wallet/assets/7074983/811799ab-4ab7-4fa8-99f8-37a7214ba6e9" /> |

2024-05-28 22:29 UTC, LuizAsFight requested changes
`gasLimit` should start with current transaction gasLimit

2024-05-28 22:42 UTC, LuizAsFight commented
if you want, you can also include #1295 in this PR. or in a next PR would be fine also.

up to you

2024-06-05 14:03 UTC, HoTandy reviewed
I've spoken to @helciofranco about this PR, we agreed that I would comment for now.  I found the following problems when reviewing this PR.

https://github.com/FuelLabs/fuels-wallet/issues/1352
https://github.com/FuelLabs/fuels-wallet/issues/1353
https://github.com/FuelLabs/fuels-wallet/issues/1354
https://github.com/FuelLabs/fuels-wallet/issues/1355
https://github.com/FuelLabs/fuels-wallet/issues/1356
https://github.com/FuelLabs/fuels-wallet/issues/1357

2024-07-25 22:41 UTC, LuizAsFight approved these changes

2024-07-25 22:41 UTC, merged