feat: validate asset names during e2e contract tests
FuelLabs/fuels-wallet pull request #1319
Opened 2024-05-28 23:05 UTC by arthurgeron

- Added aria labels to Recipient Sender and Asset Name on transaction approval screen;
- Create util for checking text content on multiple aria labels;
- Validate all asset names during e2e contract tests on the transaction approval screen, executes validation on all e2e contract test files.

2024-05-31 22:59 UTC, LuizAsFight requested changes

2024-05-31 22:59 UTC, LuizAsFight commented on packages/app/src/systems/Asset/components/AssetsAmount/AssetsAmount.tsx
> +                  {title}ss
leftover?

2024-06-03 14:19 UTC, arthurgeron commented on packages/app/src/systems/Asset/components/AssetsAmount/AssetsAmount.tsx
> +                  {title}ss
Yes! Good catch, thanks

2024-06-28 18:48 UTC, LuizAsFight approved these changes

2024-06-28 18:49 UTC, merged