feat(receive-screen): wip adds QR Code component and user component
FuelLabs/fuels-wallet pull request #137
Opened 2022-10-06 10:02 UTC by LFSCamargo

[#41](https://github.com/FuelLabs/fuels-wallet/issues/41)

2022-10-06 15:38 UTC, luizstacio commented
Also, sizes are different from the design;
1. The thumbnail should have 100x100
2. Cards have more space in the design

2022-10-11 22:49 UTC, luizstacio requested changes

2022-10-11 22:49 UTC, luizstacio commented on packages/app/package.json
> +    "jsqr": "^1.4.0",
Move this to `devDependencies` as it is used only on development

2022-10-11 22:49 UTC, luizstacio commented on packages/app/src/systems/Home/routes.tsx
> +import { Receive } from './pages/Receive';
Export Receive on the `./pages/index.tsx`

2022-10-11 22:53 UTC, luizstacio requested changes
<img width="397" alt="Screen Shot 2022-10-11 at 7 51 04 PM" src="https://user-images.githubusercontent.com/3941923/195212803-ed6202da-2d1a-4d8e-8888-a9f21bca46de.png">
1. Resize the thumbnail
2. Address should show more characters
3. Download QRCode doesn't work
<img width="943" alt="Screen Shot 2022-10-11 at 7 50 48 PM" src="https://user-images.githubusercontent.com/3941923/195212875-c2f6c021-d212-4473-a1de-e6b04b25d1d5.png">

2022-10-18 18:34 UTC, luizstacio requested changes

2022-10-18 18:34 UTC, luizstacio commented on packages/app/package.json
> +    "@fuel-ui/react": "0.8.0-dev-501df54",
```suggestion
    "@fuel-ui/react": "^0.8.0",
```

2022-10-20 15:27 UTC, luizstacio submitted a review, later dismissed

2022-10-25 20:30 UTC, luizstacio requested changes

2022-10-25 20:30 UTC, luizstacio commented on packages/app/src/systems/Home/components/UserAddressCard/UserAddressCard.tsx
> +      css={{
Move css to styles cost

2022-10-25 20:46 UTC, luizstacio submitted a review, later dismissed

2022-10-25 21:27 UTC, LuizAsFight requested changes

2022-10-25 21:27 UTC, LuizAsFight commented on packages/app/src/systems/Home/components/UserAddressCard/UserAddressCard.stories.tsx
> +    <UserAddressCard account="fuel1auahknz6mjuu0am034mlggh55f0tgp9j7fkzrc6xl48zuy5zv7vqa07n30" />
`fuel1auahknz6mjuu0am034mlggh55f0tgp9j7fkzrc6xl48zuy5zv7vqa07n30` is informed, but screen is missing the last `0`, showing only: 
`fuel1auahknz6mjuu0am034mlggh55f0tgp9j7fkzrc6xl48zuy5zv7vqa07n3` 

is this expected?

2022-10-25 21:27 UTC, LuizAsFight commented on packages/app/src/systems/Home/components/QRCode/QRCode.tsx
> +          value={account as string}
account is a string already, do we need to `as string`?

2022-10-25 21:27 UTC, LuizAsFight commented on packages/app/src/systems/Home/components/UserAddressCard/UserAddressCard.tsx
> +      <Avatar.Generated hash={account as string} size="2xl" background="fuel" />
`account` is a `string` already. do we need to `as string` ?

2022-10-25 21:27 UTC, LuizAsFight commented on packages/app/src/systems/Home/components/UserAddressCard/UserAddressCard.tsx
> +      <Avatar.Generated hash={account as string} size="2xl" background="fuel" />
change prop name to `address`.

as we use `account` in other places refferring to `Account` type, it can be confusing.

2022-10-25 21:27 UTC, LuizAsFight commented on packages/app/src/systems/Home/components/QRCode/QRCode.tsx
> +  account: string;
change prop name to address.

as we use account in other places refferring to Account type, it can be confusing

2022-10-25 21:27 UTC, LuizAsFight commented on packages/app/src/systems/Home/pages/Receive/Receive.tsx
> +          <UserAddressCard account={account?.address as string} />
we're using too many `as string` . we should avoid it.

can use a conditional before the render to make sure account is there:

```
{ account && (
<UserAddressCard account={account?.address} />
) }
```

2022-10-25 21:27 UTC, LuizAsFight commented on packages/app/src/systems/Home/routes.tsx
> +          <Outlet />
do we need to include `<Outlet />` here? `Home` had it because we might need go to Faucet route

2022-10-27 17:35 UTC, luizstacio submitted a review, later dismissed

2022-10-28 21:01 UTC, LuizAsFight requested changes
just a chore

2022-10-28 21:13 UTC, LuizAsFight approved these changes

2022-10-28 21:14 UTC, luizstacio approved these changes

2022-10-28 21:14 UTC, merged