feat: creating an e2e test for custom fees
FuelLabs/fuels-wallet pull request #1405
Opened 2024-07-05 21:26 UTC by rodrigobranas

- Closes #1301 

Also fixing format for txFee

2024-07-06 17:06 UTC, arthurgeron approved these changes

2024-07-08 17:57 UTC, LuizAsFight approved these changes

2024-07-08 17:58 UTC, LuizAsFight approved these changes

2024-07-08 18:41 UTC, LuizAsFight requested changes
1- test looking a bit flaky in the fee value check between Send and Approve screen
2- add another test case for sending a transaction using directly the "Regular fee"

2024-07-09 19:28 UTC, LuizAsFight approved these changes

2024-07-09 19:28 UTC, merged