feat: create connection request screen
FuelLabs/fuels-wallet pull request #156
Opened 2022-10-20 21:40 UTC by luizstacio

Create connection request screen, the complete feature will be implemented after when #147 is merged

2022-10-21 01:49 UTC, pedronauck requested changes

2022-10-21 01:49 UTC, pedronauck commented on packages/app/src/systems/DApp/pages/ConnectionRequest/ConnectionRequest.tsx
> +const PermissionsList = [
I guess this should follow the pattern of `SNAKE_CASE` since it's a `const`

2022-10-21 01:49 UTC, pedronauck commented on packages/app/src/systems/DApp/pages/ConnectionRequest/ConnectionRequest.tsx
> +const NotAllowedList = ['View your private keys'];
here also

2022-10-25 19:38 UTC, LFSCamargo submitted a review, later dismissed
LGTM

2022-10-25 21:28 UTC, pedronauck approved these changes

2022-10-25 22:04 UTC, LuizAsFight approved these changes

2022-10-25 22:25 UTC, merged