fix: account name checks FE-724
FuelLabs/fuels-wallet pull request #1570
Opened 2024-10-09 14:33 UTC by nelitow

- Closes https://github.com/FuelLabs/fuels-wallet/issues/1263

Fixes:
- User not being able to change the account name to case-sensitive variations of the same word.
  - Example: Changing a case typo, like **Fuel wAllet** -> **Fuel Wallet** was not possible
- User not being able to change or create accounts that are substring of eachother.
  - Example: Changing **Fuel Wallet** -> **Wallet** was not possible

Considerations:
- The `filterByName` function sound like it could be used for a search filter, in which it should be case insensitive, but that is not the case at the moment, it is only used for account name editing and creation.
- Users can now create multiple accounts with similar names, which can cause confusion, changing only a letter case, so:
  - **Account 1** and **account 1** can now coexist as account names

2024-10-09 14:36 UTC, helciofranco approved these changes
LGTM, your consideration about name conflicts is fine.

for reference, check rabby wallet, they allow even same exact name:
| Rabby Wallet |
| --- |
| <img width="237" alt="Screenshot 2024-10-09 at 10 35 43" src="https://github.com/user-attachments/assets/a8258f8a-2acf-470a-8640-2961f6e19ccc"> |

2024-10-09 14:38 UTC, helciofranco commented
it's missing to add a changeset @nelitow 

`pnpm changeset`

2024-10-09 14:52 UTC, helciofranco commented on packages/app/src/systems/Account/services/account.ts
> +      account.name === name;
it's missing a return clause here

```suggestion
      return account.name === name;
```

2024-10-09 15:41 UTC, helciofranco submitted a review, later dismissed

2024-10-10 06:46 UTC, LuizAsFight requested changes
this broke the test that validates connected screen flow.


the comparison before was done with `includes` and now it's done with `===` what was the reason for changing this? the issue was to fix the lowerCase only

2024-10-11 03:39 UTC, LuizAsFight approved these changes

2024-10-11 03:39 UTC, merged