fix: balance format precision with tooltips
FuelLabs/fuels-wallet pull request #1571
Opened 2024-10-09 19:46 UTC by helciofranco

- Closes https://github.com/FuelLabs/fuels-wallet/issues/1564

---

I've also removed the `balances` from our browser storage. Let's keep it fetching directly from the node.

| 📷  Tiny | Regular | Huge |
| --- | --- | --- |
| <img width="380" alt="small amounts" src="https://github.com/user-attachments/assets/0994b6c5-20f7-468f-be39-6d741b960f11"> | <img width="386" alt="not so small" src="https://github.com/user-attachments/assets/9384c85a-f73f-4cde-a549-e8888e9cdfdc"> |<img width="374" alt="huge amount" src="https://github.com/user-attachments/assets/383f0bec-c8df-44c1-b608-e3f484541c61"> |

2024-10-10 06:56 UTC, LuizAsFight requested changes
this PR is changing too much, the issue aims to fix the balance only, but I see the Approve Transaction screen is showing balance with <0.00001. Revert the changes in places we don't want and keep them only for showing correct balances.

2024-10-10 16:36 UTC, arthurgeron commented on packages/app/src/systems/Account/components/BalanceAssets/BalanceAssets.tsx
> +          showActions={false}
default is false

2024-10-10 23:36 UTC, LuizAsFight requested changes
2 problems here
- its showing wrong balance for the unknown tokens, before it was with zero units and now it's using like 9 units
- tooltip is showing only 0

<img width="347" alt="image" src="https://github.com/user-attachments/assets/3db88187-3cef-449b-ab3d-a9fa22bc978b">

2024-10-11 00:23 UTC, helciofranco commented
@LuizAsFight nice catch, fixes has been pushed.

2024-10-11 03:24 UTC, LuizAsFight approved these changes

2024-10-11 03:24 UTC, merged