feat: add contract info display for testnet contracts
FuelLabs/fuels-wallet pull request #1708
Opened 2024-12-12 21:46 UTC by akintewe

- Add support for displaying contract names and logos in transaction approval screen
- Support both mainnet and testnet (sepolia) contracts
- Fetch contract info from fuel-ecosystem registry

2024-12-13 09:44 UTC, LuizAsFight requested changes
thanks for the contribution!

this issue aims to have the UI version working , with the contract and name showing up on the approval screen, you plan to add that?

2024-12-13 10:14 UTC, akintewe commented
> thanks for the contribution!
> 
> this issue aims to have the UI version working , with the contract and name showing up on the approval screen, you plan to add that?

yes i plan to add that

2024-12-14 09:19 UTC, LuizAsFight requested changes
some issues here:
1- its not showing correct, see prints this contract is detected on explorer but not in wallet
2- to test this you can connect to mainnet and interact directly with Fuel Bridge (you need to change in your .env the env 
3- this needs to work on all transaction views, as they are all the same component this can be done in a reusable component instead of in TxApprove component. You can test by accessing Transaction History, by "Send Page" iunside the wallet and also asking for approval from external dapp
from
```
VITE_CRX_NAME="Fuel Wallet Development"
```
to 
```VITE_CRX_NAME="Fuel Wallet"
```
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/ff0580b7-18c5-4937-8239-54bdf175b043" />
<img width="328" alt="image" src="https://github.com/user-attachments/assets/1b5ead83-867d-4df1-a718-914d83866cc8" />

2024-12-15 17:54 UTC, akintewe commented
> some issues here: 1- its not showing correct, see prints this contract is detected on explorer but not in wallet 2- to test this you can connect to mainnet and interact directly with Fuel Bridge (you need to change in your .env the env 3- this needs to work on all transaction views, as they are all the same component this can be done in a reusable component instead of in TxApprove component. You can test by accessing Transaction History, by "Send Page" iunside the wallet and also asking for approval from external dapp from
> 
> ```
> VITE_CRX_NAME="Fuel Wallet Development"
> ```
> 
> to
> 
> <img alt="image" width="1156" src="https://private-user-images.githubusercontent.com/8636507/395768506-ff0580b7-18c5-4937-8239-54bdf175b043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODUwMjYsIm5iZiI6MTczNDI4NDcyNiwicGF0aCI6Ii84NjM2NTA3LzM5NTc2ODUwNi1mZjA1ODBiNy0xOGM1LTQ5MzctODIzOS01NGJkZjE3NWIwNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTc0NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njc4NWFiZjQwNDRjMjRhYTgzZjZiMzM3NDEzNzdiOTAzZTU0MjE0MDMxNDI0Y2E2YjI0YzZiNGNiYzNhYTYxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OhQf9jU_eaOShMsdsF-V3kukdwOkY_J5AkIYY9TnwMg"> <img alt="image" width="328" src="https://private-user-images.githubusercontent.com/8636507/395768582-1b5ead83-867d-4df1-a718-914d83866cc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODUwMjYsIm5iZiI6MTczNDI4NDcyNiwicGF0aCI6Ii84NjM2NTA3LzM5NTc2ODU4Mi0xYjVlYWQ4My04NjdkLTRkZjEtYTcxOC05MTRkODM4NjZjYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTVUMTc0NTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzMxNDk1OTE0MzE4NTNhNzljMzRjMmY4ZWMyZDVmZjJkNDBkNjRmMGM2NTY0ZmUzMzgyZTc1YWVkM2I5MDkwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WMUiPmhS_IWiN0Ne0ilgNTNTPxDFOTUVJ2CwVrtw1W0">

Is there a faucet i can use to fund mainnet, because i was only able to test with testnet and its still showing unknown

2025-01-02 07:01 UTC, helciofranco commented
Closed by https://github.com/FuelLabs/fuels-wallet/pull/1749

2025-01-02 07:01 UTC, closed without merging