feat: Add Network Status
FuelLabs/fuels-wallet pull request #1726
Opened 2024-12-17 23:04 UTC by DanielEmmanuel1

2024-12-21 23:42 UTC, DanielEmmanuel1 commented
@LuizAsFight  Please can u review this please

2024-12-24 06:30 UTC, LuizAsFight commented
@DanielEmmanuel1 can you post a prinscreen of how its looking, in the pr description?

2024-12-24 06:32 UTC, LuizAsFight requested changes

2024-12-24 06:32 UTC, LuizAsFight commented on packages/app/src/systems/Send/components/SendSelect/SendSelect.tsx
> +              </HStack>
can you separate this in a component and make it don't show by default?

2024-12-27 13:20 UTC, DanielEmmanuel1 commented
@LuizAsFight Please review

2025-01-08 11:17 UTC, DanielEmmanuel1 commented
Screenshots as requested
![WhatsApp Image 2025-01-08 at 12 04 46_38edd253](https://github.com/user-attachments/assets/be495edb-de2c-4751-93e6-51c02e6f3c54)

2025-01-17 11:40 UTC, closed without merging