chore: remove dependency override for `enhanced-resolve`
FuelLabs/fuels-wallet pull request #254
Opened 2022-11-23 20:17 UTC by LuizAsFight

Closes #251

2022-11-24 03:06 UTC, pedronauck requested changes

2022-11-24 03:06 UTC, pedronauck commented on .lintstagedrc
> +  "*.{js,jsx,ts,tsx,html}": ["pnpm prettier:check", "pnpm lint:check"]
This is the right definition for `lintstaged`:

```json
{
  "*.{js,jsx,ts,tsx,html}": [
    "prettier --check",
    "eslint"
  ],
  ".{ts,tsx}": [
    "tsc --noEmit"
  ]
}
```

2022-11-24 11:03 UTC, luizstacio approved these changes

2022-11-24 11:42 UTC, luizstacio approved these changes

2022-11-25 00:44 UTC, pedronauck approved these changes

2022-11-25 00:50 UTC, merged