feat: persist balance visibility after page reload
FuelLabs/fuels-wallet pull request #287
Opened 2022-11-30 18:51 UTC by tomiiide

## What does this PR do?
Fixes #119 
This PR makes the Wallet Balance Visibility persistent on page reload.

2022-11-30 19:56 UTC, luizstacio requested changes
We should add some tests for this action.

2022-11-30 19:56 UTC, luizstacio commented on packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.tsx
> +import type { AccountInputs } from '../..';
inside the components, you should import from the components folder to avoid cycle dependencies.

2022-11-30 19:56 UTC, luizstacio commented on packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.tsx
> +            onHide={() => toggleBalanceVisibility(true)}
The name of the function was better before, toggle would be better for a function that doesn't receive the state. But in this case, we explicitly set is visible or not.

```suggestion
            onHide={() => setBalanceVisibility(true)}
```

2022-11-30 23:25 UTC, LuizAsFight approved these changes

2022-11-30 23:25 UTC, LuizAsFight requested changes
code looks good, but tests are failing, need to fix it

2022-11-30 23:47 UTC, luizstacio requested changes

2022-11-30 23:47 UTC, luizstacio commented on packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.tsx
> +  onSetBalanceVisibility?: (
```suggestion
  onChangeBalanceVisibility?: (
```

2022-11-30 23:50 UTC, luizstacio requested changes

2022-11-30 23:50 UTC, luizstacio commented on packages/app/src/systems/Account/components/BalanceWidget/BalanceWidget.tsx
> +import type { AccountInputs } from '~/systems/Account';
```suggestion
import type { AccountInputs } from '~/systems/Account/services';
```

2022-12-02 08:59 UTC, luizstacio approved these changes

2022-12-02 21:45 UTC, merged