fix: service worker path
FuelLabs/fuels-wallet pull request #335
Opened 2022-12-06 03:51 UTC by luizstacio

2022-12-06 14:28 UTC, LuizAsFight requested changes
still not working when testing in `preview` storybook...


https://user-images.githubusercontent.com/8636507/205938509-a9cf871e-a488-473e-aaf8-e359939d482e.mov

- `No Assets` and `With Assets` pages are never leaving loading state
- `With Assets` should show balance

2022-12-06 19:52 UTC, luizstacio commented
> still not working when testing in `preview` storybook...
> 
>  Screen.Recording.2022-12-06.at.11.27.19.mov 
> * `No Assets` and `With Assets` pages are never leaving loading state
> * `With Assets` should show balance

I open an issue to track it that is on description #336. We can move with this one and fix this one later.

2022-12-06 21:34 UTC, pedronauck approved these changes
Lgfm

2022-12-07 03:08 UTC, LuizAsFight approved these changes

2022-12-07 03:08 UTC, merged