refactor: update the bn.format calls to use the default params
FuelLabs/fuels-wallet pull request #347
Opened 2022-12-07 10:51 UTC by tomiiide

Fixes #198

2022-12-08 19:02 UTC, luizstacio requested changes

2022-12-09 13:56 UTC, LuizAsFight requested changes
code looks good.

recently @luizstacio introduced this function -> `formatFullAmount`, which:
- became pretty useless now with SDK changes
- it's being used only in 1 place

can you remove this function, and in the screen that uses it, replace to a simple `bn(amount).format()` ??

2022-12-12 18:12 UTC, LuizAsFight approved these changes

2022-12-12 18:26 UTC, luizstacio approved these changes

2022-12-12 18:27 UTC, merged