feat: add account screen
FuelLabs/fuels-wallet pull request #373
Opened 2022-12-17 05:02 UTC by matt-user

closes #23

2022-12-23 01:42 UTC, LuizAsFight requested changes

2022-12-23 01:42 UTC, LuizAsFight commented on packages/app/src/systems/Account/machines/unlockMachine.tsx
>        }),
can we create other service / event for `unlockManager` ?

who needs the `manager` fires event `UNLOCK_MANAGER`.
who needs the `wallet` fires event `UNLOCK_MANAGER`

2022-12-23 01:42 UTC, LuizAsFight commented on packages/app/src/systems/Account/machines/unlockMachine.tsx
>        }),
after doing it can also remove the `input.manager: boolean`

2022-12-23 03:16 UTC, luizstacio commented on packages/app/src/systems/Account/machines/accountMachine.tsx
> +      },
This machine is never idle, as the account list is triggered every 15 seconds,

2022-12-23 21:54 UTC, pedronauck requested changes

2022-12-24 00:36 UTC, pedronauck approved these changes

2022-12-24 01:28 UTC, luizstacio approved these changes

2022-12-24 01:29 UTC, LuizAsFight approved these changes

2022-12-24 01:29 UTC, merged