feat: create tx history screen
FuelLabs/fuels-wallet pull request #410
Opened 2023-01-02 12:15 UTC by tomiiide

This PR creates the activity screen, that shows a users transactions.

closes #28 

https://www.loom.com/share/342981fa3c004d8f90b4036a377f3a00

2023-01-09 23:48 UTC, pedronauck requested changes

2023-01-09 23:48 UTC, pedronauck commented on packages/app/src/systems/Transaction/hooks/useTxs.tsx
> +  switch (receipt.type) {
This should not be a simple `if (ReceiptType.ReturnData || ReceiptType.LogData)` instead of a switch? 🤔

2023-01-09 23:48 UTC, pedronauck commented on packages/app/src/systems/Transaction/machines/transactionsMachine.tsx
> +    id: 'FETCH ADDRESS TRANSACTIONS',
try to follow the pattern we already have in other machines here for `states` names and machine `id`

2023-01-09 23:48 UTC, pedronauck commented on packages/app/src/systems/Transaction/machines/transactionsMachine.tsx
> +export const transactionsMachine = createMachine(
Sorry, but why you have this machine here if you're not using it?

2023-01-09 23:48 UTC, pedronauck commented on packages/app/src/systems/Transaction/hooks/useTxs.tsx
> +  const { loading, data, error } = useAddressTransactionsQuery({
I have my concerns about using this to fetch instead of machines like we are doing in the entire application.

2023-01-09 23:48 UTC, pedronauck commented on packages/app/src/systems/Transaction/pages/ViewActivity/ViewActivity.tsx
> +  const addressQueryParam = useParams<{ address: string }>().address;
These entire code should be inside a `useActivity` hook

2023-01-18 23:46 UTC, luizstacio requested changes

2023-01-18 23:46 UTC, luizstacio commented on packages/app/src/systems/Core/utils/graphql.tsx
> +const client = new GraphQLClient('http://localhost:4000/graphql');
The provider needs to user the current network selected by the users.

2023-01-18 23:46 UTC, luizstacio commented on packages/app/src/systems/Transaction/pages/ViewActivity/ViewActivity.tsx
> +      <Layout.TopBar onBack={() => navigate(-1)} />
Once navigating to the page the back button should return to wallet.

If you click multiple times on the Acitivity item you need to click multiple times before it returns to the wallet.

2023-01-19 02:09 UTC, luizstacio approved these changes

2023-01-19 02:58 UTC, luizstacio approved these changes

2023-01-19 03:23 UTC, luizstacio approved these changes

2023-01-19 03:29 UTC, merged