feat: improve fuel injection
FuelLabs/fuels-wallet pull request #541
Opened 2023-02-04 00:34 UTC by luizstacio

This PR improves how we detect when fuel is injected on the page. With this PR now, it's possible to listen for an event on the document object `FuelLoaded` this name makes reference to `DOMContentLoaded`. This event is triggered right after the fuel object is assigned to the target object, in this case, the window.

This PR also adds a new handler to `onInstall` event. The new handler injects `fuel` into the tabs already open, removing the need to refresh the page.

These two improvements enable applications to listen to the event `FuelLoaded`, and once the user installs the Wallet, the application can start work without the need for workarounds or request for the user to refresh the page.

close: #308

2023-02-04 11:25 UTC, tomiiide commented on packages/docs/docs/how-to-use.mdx
> +It's possible that your applaction loads before `window.fuel` is injected. To detect when the `fuel` is loaded and ready to use, you can listen to the event `FuelLoaded` on the document.
```suggestion
It's possible that your application loads before `window.fuel` is injected. To detect when the `fuel` is loaded and ready to use, you can listen to the event `FuelLoaded` on the document.
```

2023-02-04 11:31 UTC, tomiiide requested changes
Looks good, just one little typo.

2023-02-06 11:33 UTC, tomiiide approved these changes
Looks good now.

2023-02-06 12:17 UTC, eswarasai commented on packages/docs/examples/FuelLoaded.tsx
> +    // On unmount, remove the event listener and clear the timeout
```suggestion
    // On unmount, remove the event listener
```

2023-02-06 15:12 UTC, LuizAsFight approved these changes

2023-02-06 15:16 UTC, LuizAsFight requested changes
tests breaking after merging with master

2023-02-06 16:32 UTC, merged