docs: add overlay to examples when fuel is not detected
FuelLabs/fuels-wallet pull request #552
Opened 2023-02-08 21:42 UTC by tomiiide

closes #276.

This PR adds an overlay to examples in the docs when fuel is not detected on the browser, this way the user cannot interact with the examples.

![Screenshot 2023-02-08 at 9 42 33 PM](https://user-images.githubusercontent.com/15849997/217657742-edcd3ea3-892c-424e-9471-91a70a3d6be6.png)

2023-02-08 22:06 UTC, pedronauck submitted a review, later dismissed

2023-02-08 22:20 UTC, luizstacio requested changes

2023-02-08 22:20 UTC, luizstacio commented on packages/docs/src/components/ExampleBox.tsx
> +    </Stack>
As the space is small and the message can be repetitive maybe just add:

`Wallet not detected`
`Add a link to install page`

2023-02-09 14:04 UTC, luizstacio approved these changes

2023-02-09 14:07 UTC, merged