feat:  improve permission, account, and connection info on all screens.
FuelLabs/fuels-wallet pull request #589
Opened 2023-02-23 16:14 UTC by tomiiide

This PR contains a bunch of minor fixes and updates:
1. Improves the permission info on the connection screen
2. Updates the Signer Info to the new UI on the all Popup screens.
3. Updates the origin info to the new UI on all Popup screens.
4. Some code refactors.

closes #437, #483 and #482

Demo:
https://www.loom.com/share/277d8d2f235c4164a4e0ddbb177433db

2023-02-25 10:01 UTC, akharito1975 approved these changes

2023-02-25 19:51 UTC, luizstacio requested changes
Can you remove the https:// and http:// it should just the domain origin.
<img width="342" alt="Screenshot 2023-02-25 at 16 50 19" src="https://user-images.githubusercontent.com/3941923/221376802-c9e80c5a-f4b7-410b-8ddc-5776a4c7a92a.png">

2023-02-26 20:37 UTC, LuizAsFight requested changes
AccountInfo Loader has different height of AccountInfo component, and also loader elements are not quite in the same place

2023-02-26 20:57 UTC, LuizAsFight requested changes

2023-02-26 20:57 UTC, LuizAsFight commented on packages/app/src/systems/Core/components/PermissionCard/mocks/PERMISSIONS.tsx
> +export const PERMISSION_LIST = [
can we rename this file to `permissions.tsx` ?

2023-02-26 20:57 UTC, LuizAsFight commented on packages/app/src/systems/Settings/components/ConnectionEdit/ConnectionEdit.tsx
> +        {/* <Text leftIcon={Icon.is('Globe')} css={styles.title}>
can we remove the comment ?

2023-02-27 04:41 UTC, tomiiide commented
> AccountInfo Loader has different height of AccountInfo component, and also loader elements are not quite in the same place

Fixed, thanks for this.

2023-02-27 15:44 UTC, luizstacio requested changes
- On the signing screen, the header can be removed
<img width="364" alt="Screenshot 2023-02-27 at 12 41 19" src="https://user-images.githubusercontent.com/3941923/221609630-90d12db0-d3e4-4268-8f31-a529596c7401.png">

2023-02-27 15:56 UTC, luizstacio requested changes

2023-02-27 15:56 UTC, luizstacio commented on packages/app/playwright/crx/crx.test.ts
> -        await getButtonByText(confirmTransactionPage, /confirm/i).click();
The sender account name is essential in this test to ensure it shows the expected account on the approval screen.

2023-02-27 15:56 UTC, luizstacio commented on packages/app/src/systems/Core/components/AccountInfo/AccountInfo.stories.tsx
> +);
We can improve here using a template and just changing the params argument. Take a look on ContentHeader story.

2023-02-27 16:10 UTC, tomiiide commented
> * On the signing screen, the header can be removed
> 
> <img alt="Screenshot 2023-02-27 at 12 41 19" width="364" src="https://user-images.githubusercontent.com/3941923/221609630-90d12db0-d3e4-4268-8f31-a529596c7401.png">

what header are you referring to?

The 'Signing a messsage to:' section, or the 'Signature Request' section?

2023-02-27 16:33 UTC, luizstacio commented on packages/app/playwright/crx/crx.test.ts
> -        await getButtonByText(confirmTransactionPage, /confirm/i).click();
> But we don't show the account name on the approval screen, we only show the address. ![Screenshot 2023-02-27 at 4 27 36 PM](https://user-images.githubusercontent.com/15849997/221622301-169de1e0-8d8e-4cb6-933e-22f57395adfc.png) ![Screenshot 2023-02-27 at 4 27 40 PM](https://user-images.githubusercontent.com/15849997/221622305-f990f8ae-683c-437f-8fc9-e96eef1654df.png)

The test search for a aria-label, with the name of the account you can add it to the Account Details component, or change the test to check by the address.

2023-02-27 18:07 UTC, LuizAsFight commented
> * On the signing screen, the header can be removed
> 
> <img alt="Screenshot 2023-02-27 at 12 41 19" width="364" src="https://user-images.githubusercontent.com/3941923/221609630-90d12db0-d3e4-4268-8f31-a529596c7401.png">

it's not important to show current network? that's the only purpose of header now with new components... maybe we can think on a solution to show the network when needed, and remove header from all DAPP screens?

2023-02-28 19:06 UTC, LuizAsFight commented
> > * On the signing screen, the header can be removed
> > 
> > <img alt="Screenshot 2023-02-27 at 12 41 19" width="364" src="https://user-images.githubusercontent.com/3941923/221609630-90d12db0-d3e4-4268-8f31-a529596c7401.png">
> 
> it's not important to show current network? that's the only purpose of header now with new components... maybe we can think on a solution to show the network when needed, and remove header from all DAPP screens?

cc @luizstacio

2023-02-28 19:17 UTC, LuizAsFight commented
now `DAPP/Approve Transaction Screen` is the only screen that has the header.

I suggest we remove it, as:
- now we already use AccountInfo component showing screen title as header
- current Header only purpose is show the network
- it's a too discrete place to show the network
 
 
we should:
- remove header component
- show network in other place, adding more relevance to it in layout hierarchy 
  - could be a card between Confirm / TxFromTo


doesn't need to be done in this PR but we can open an issue to fix it later if you guys agree @luizstacio @tomiiide 
![image](https://user-images.githubusercontent.com/8636507/221955336-cd3a5dda-5caf-4899-9602-b6d5f593bac8.png)

2023-03-01 12:18 UTC, tomiiide commented
> Confirm block is looking to big:
> 
> * decrease font-size by 2px for yellow(title) and gray(subtitle)
> * decrease margin between title and subtitle
> 
> ![image](https://user-images.githubusercontent.com/8636507/222014235-a605bd5a-2bce-4948-835e-bdf340ebc699.png)

![Screenshot 2023-03-01 at 12 10 22 PM](https://user-images.githubusercontent.com/15849997/222137168-140a25ed-f6fd-486c-9587-7728058a0caa.png)
Is this better?

2023-03-01 15:17 UTC, LuizAsFight approved these changes

2023-03-01 15:17 UTC, LuizAsFight commented
awesome work @tomiiide

2023-03-01 15:40 UTC, luizstacio approved these changes

2023-03-01 15:40 UTC, merged