feat: support insert multiple assets via SDK fuel.addAsset
FuelLabs/fuels-wallet pull request #593
Opened 2023-02-24 23:57 UTC by LuizAsFight

Closes #584

2023-02-27 02:06 UTC, luizstacio requested changes
I found two things;
1. When adding an asset manually inside the Wallet. Assets page, add a new asset, add an asset_id that already exists, add name and symbol, and click on save. The Wallet just updates a current asset without alerting it that already exists and blocking the action.
2. On the origin info is showing the wrong domain.

<img width="401" alt="Screenshot 2023-02-26 at 22 59 56" src="https://user-images.githubusercontent.com/3941923/221455264-7719d997-fa13-49b2-8a92-5bade069f112.png">

2023-02-27 15:26 UTC, LuizAsFight commented
> I found two things;
> 
> 1. When adding an asset manually inside the Wallet. Assets page, add a new asset, add an asset_id that already exists, add name and symbol, and click on save. The Wallet just updates a current asset without alerting it that already exists and blocking the action.
> 2. On the origin info is showing the wrong domain.
> 

About point 1. I think we can do in another issue / PR as it's orthogonal to this issue/PR objective
https://github.com/FuelLabs/fuels-wallet/issues/598

2023-02-28 16:18 UTC, luizstacio requested changes

2023-02-28 16:56 UTC, luizstacio approved these changes

2023-02-28 16:56 UTC, merged