582-create-terms-of-use-page
FuelLabs/fuels-wallet pull request #596
Opened 2023-02-27 10:12 UTC by tomiiide

This PR creates the terms and agreement page.

closes #582

2023-02-28 16:26 UTC, luizstacio requested changes
We should hold this PR until we update the ToS content

2023-04-24 20:50 UTC, luizstacio approved these changes

2023-04-24 21:41 UTC, LuizAsFight requested changes

2023-04-24 21:41 UTC, LuizAsFight commented on packages/app/src/systems/SignUp/pages/TermsOfUse/TermsOfUse.tsx
> +          subtitle="Read and accept our terms of service"
```suggestion
          subtitle="Check if you accept our terms of service"
```

2023-04-24 21:41 UTC, LuizAsFight commented
e2e tests are broken

2023-04-28 20:35 UTC, luizstacio commented on packages/app/src/systems/SignUp/pages/TermsOfUse/data/terms.md
> +# Fuel Wallet Testnet Terms Of Use Agreement
```suggestion
## Fuel Wallet Testnet Terms Of Use Agreement
```

2023-04-28 20:35 UTC, luizstacio commented on packages/app/src/systems/SignUp/pages/TermsOfUse/TermsOfUse.tsx
> +          title="Terms of Service"
```suggestion
          title="Terms of use Agreement"
```

2023-04-28 20:57 UTC, luizstacio approved these changes

2023-04-28 20:59 UTC, LuizAsFight approved these changes

2023-04-28 20:59 UTC, merged