feat(app): add AssetItem and AssetList components
FuelLabs/fuels-wallet pull request #66
Opened 2022-08-26 04:17 UTC by pedronauck

✨ Fix #8 
✨ Fix #9

2022-08-26 04:27 UTC, pedronauck commented
@luizstacio I ended up choosing `react-content-loader` because is possible to just copy SVG from Figma and [paste it into their website](https://skeletonreact.com/) to generate the right loader, that the result:

- https://fuels-wallet-bdzlegv2g-fuel-labs.vercel.app/storybook/?path=/story/asset-assetlist--loading

And [that's the code](https://github.com/FuelLabs/fuels-wallet/pull/66/files#diff-1d26fb48666109b7776bbe6ac934219e2eb129a0523faa105bb1170785f71a2f)

2022-08-26 15:57 UTC, luizstacio requested changes
I think the copy action is not in the correct place; on the design it just appears on the side of the address, but when inside the AssetList we should don't have.

2022-08-26 23:22 UTC, luizstacio requested changes

2022-08-26 23:22 UTC, luizstacio commented on packages/app/src/systems/Core/utils/math.tsx
> +import * as ethers from "ethers";
We should remove ethers and add a custom code in the places it is needed.

2022-08-27 00:22 UTC, luizstacio approved these changes

2022-08-27 00:22 UTC, merged