Fix: typos
FuelLabs/fuels-wallet pull request #675
Opened 2023-04-07 11:09 UTC by omahs

Fix: typos

2023-04-10 11:32 UTC, tomiiide commented on packages/docs/docs/how-to-use.mdx
> +If you are using react take a look at the source code of the example below to see how we implement it.
```suggestion
If you are using react, take a look at the source code of the example below to see how we implement it.
```

2023-04-10 12:53 UTC, tomiiide requested changes
Looks good, just a little typo improvement.

2023-04-10 13:38 UTC, omahs commented
Just updated!

2023-04-13 05:30 UTC, LuizAsFight approved these changes

2023-04-25 09:38 UTC, omahs commented
@luizstacio It seems that the files were updated already and typos were fixed so I'll close this :)

2023-04-25 09:38 UTC, closed without merging