fix: observe connection deletion
FuelLabs/fuels-wallet pull request #726
Opened 2023-04-28 18:59 UTC by matt-user

Add listener to databaseObservable in order to broadcast that a connection has been deleted from inside of the wallet.

Closes FRO-100

2023-04-28 22:19 UTC, LuizAsFight requested changes
nice @matt-user 

would be nice to add a e2e test to validate that dapp is correctly receiving the event after connection is removed in wallet side

2023-05-02 18:01 UTC, luizstacio submitted a review, later dismissed

2023-05-02 18:07 UTC, LuizAsFight requested changes

2023-05-02 18:07 UTC, LuizAsFight commented on packages/app/playwright/crx/crx.test.ts
> +      expect(await isDisonnected).toBeTruthy();
```suggestion
      expect(await isDisconnected).toBeTruthy();
```

2023-05-02 18:14 UTC, LuizAsFight approved these changes

2023-05-02 18:21 UTC, luizstacio approved these changes

2023-05-02 18:21 UTC, merged