feat: move console.debug to console.log in docs #547
FuelLabs/fuels-wallet pull request #746
Opened 2023-05-12 04:37 UTC by tibi77

2023-05-12 05:14 UTC, tibi77 commented
I can not link issues, but this is related to #547

2023-05-13 00:43 UTC, tibi77 commented
closes #547

2023-05-15 09:34 UTC, tomiiide approved these changes
LGTM.

Nice work @tibi77

2023-05-15 16:10 UTC, tibi77 commented
@tomiiide I can not merge.. so if you d do the honor

2023-05-15 19:17 UTC, LuizAsFight commented
@luizstacio need some eyes here this PR is approved but not able to be merged apparently because needs vercel 
 CI step completed... I tried to authorize but it's not moving anywhere
 
![image](https://github.com/FuelLabs/fuels-wallet/assets/8636507/f7730d87-d208-458a-b5e0-25c3e495fef7)

2023-05-15 21:09 UTC, luizstacio requested changes

2023-05-15 21:09 UTC, luizstacio commented on .changeset/honest-colts-tan.md
> +Change console debug to console log in docs
As the changes is only on the docs you can remove this changeset file.

2023-05-17 19:02 UTC, luizstacio approved these changes

2023-05-17 19:03 UTC, merged