text cleanup
FuelLabs/fuels-wallet pull request #754
Opened 2023-05-19 18:26 UTC by sarahschwartz

Some small changes to the text in the wallet to make it more concise and readable

2023-05-19 21:02 UTC, luizstacio requested changes
Just a small comment. Thanks for the review.

2023-05-19 21:19 UTC, luizstacio requested changes

2023-05-19 21:19 UTC, luizstacio commented on .changeset/shaggy-pots-shop.md
> +---
Can we add a patch update here to show the changes on text on the changelog?

2023-05-22 10:54 UTC, tomiiide approved these changes
Nice work @sarahschwartz .
Looks good.

2023-05-22 13:12 UTC, eswarasai commented on packages/app/src/systems/Settings/components/ConnectionItem/ConnectionItem.tsx
> +          {accounts} {accounts > 1 ? 'accounts' : 'account'} connected
```suggestion
          {accounts} {`account${accounts > 1 ? 's' : ''}`} connected
```

2023-05-22 15:57 UTC, luizstacio approved these changes

2023-05-22 15:58 UTC, sarahschwartz commented on packages/app/src/systems/Account/pages/ExportAccount/ExportAccount.tsx
> +              With this Private Key, you can restore your account later. Make
What do you think about this? <img width="358" alt="wallet screenshot" src="https://github.com/FuelLabs/fuels-wallet/assets/58856580/04481f77-c61b-4f9c-8d34-cf7e74c2bb0c">

2023-05-22 16:24 UTC, merged