refactor: fuel sdk
FuelLabs/fuels-wallet pull request #764
Opened 2023-05-25 12:42 UTC by eswarasai

[FRO-83](https://linear.app/fuel-network/issue/FRO-83/enable-fuelweb3-sdk-to-be-use-direct-without-the-need-to-use-the)

### Description

- [x] Added support for `Fuel` initialisation and not having to wait for `window.fuel` to be injected
```
import { FuelWeb3 } from '@fuel-wallet/sdk';
const fuelWeb3 = new FuelWeb3();

// If extension is installed, request is queued and processed as soon as `window.fuel` is available
await fuelWeb3.connect();
```

2023-05-25 13:27 UTC, luizstacio requested changes

2023-05-25 13:27 UTC, luizstacio commented on .changeset/sweet-beans-shake.md
> +Enabled FuelWeb3 SDK to be use directly without the need to wait for the injected script
```suggestion
Enabled FuelWallet SDK to be use directly without the need to wait for the injected script
```

2023-05-25 13:27 UTC, luizstacio commented on packages/sdk/src/FuelWalletConnection.ts
> +    this.timeoutTimer = setInterval(handleFuelInjected, 1000);
We should abstract this in a better way splitting the functions on utilities or on the body of the class.

2023-05-25 13:28 UTC, luizstacio requested changes
- Add some tests using jest or e2e to ensure that the new approach works as expected

2023-05-31 03:32 UTC, luizstacio requested changes

2023-05-31 03:32 UTC, luizstacio commented on packages/docs/docs/dev/getting-started.mdx
>  ```
We can break this section in two, from window and from package.

2023-05-31 03:32 UTC, luizstacio commented on packages/sdk/src/Fuel.test.ts
> +    MockConnection.start(fuel);
We should create another test file for just testing this.

2023-05-31 03:32 UTC, luizstacio commented on packages/sdk/src/FuelWalletConnection.ts
> +    this.timeoutTimer = setInterval(this.handleFuelInjected.bind(this), 100);
```suggestion
    this._injectionTimeout = setInterval(this.handleFuelInjected.bind(this), 100);
```

2023-05-31 03:32 UTC, luizstacio commented on packages/sdk/src/FuelWalletConnection.ts
> +      this.client.rejectAllPendingRequests('fuel not detected on the window!');
```suggestion
      this.client.rejectAllPendingRequests('Timeout fuel not detected on the window!');
```

2023-05-31 03:32 UTC, luizstacio commented on packages/sdk/src/FuelWalletConnection.ts
> +  retry = 1;
```suggestion
  _retry = 0;
```

2023-06-05 15:26 UTC, tomiiide submitted a review, later dismissed
LGTM!

2023-06-08 06:03 UTC, LuizAsFight requested changes

2023-06-08 06:03 UTC, LuizAsFight commented on packages/sdk/src/FuelWalletConnection.ts
>          type: MessageTypes.request,
```suggestion
  async sendRequest(request: JSONRPCRequest | null) {
    if (!request) return;
    
    if (!window.fuel) {
      this.queue.push(request);
    } else {
      this.postMessage({
        type: MessageTypes.request,
```

2023-06-12 15:17 UTC, luizstacio requested changes

2023-06-14 07:45 UTC, LuizAsFight submitted a review, later dismissed

2023-06-14 18:22 UTC, luizstacio commented on packages/sdk/src/connections/WindowConnection.ts
> +  constructor(connector: FuelWalletConnector = { name: 'Fuel Wallet' }) {
Yes we should not do this., because is intended to be used by external projects also.

2023-06-16 14:58 UTC, luizstacio approved these changes

2023-06-16 16:39 UTC, LuizAsFight approved these changes

2023-06-16 17:37 UTC, merged