feat: add error reporting tool using sentry
FuelLabs/fuels-wallet pull request #789
Opened 2023-06-20 01:43 UTC by luizstacio

This PR;
- Improves error handling for CRX
- Improve error handling UI to be less dependent on the application UI
- Change order of Providers
- Add checking on database to report also CRX errors / crashes
- Fix the UI of the error handling screen related to the top items
- Change error reporting to use Sentry instead of email

2023-06-22 22:12 UTC, LuizAsFight requested changes

2023-07-04 14:17 UTC, eswarasai commented on packages/app/.env.production
> +VITE_SENTRY_DNS=https://f9a5b923067f4f789fb40ed7eccd6486@o4505280621707264.ingest.sentry.io/4505280648577024
```suggestion
VITE_SENTRY_DSN=https://f9a5b923067f4f789fb40ed7eccd6486@o4505280621707264.ingest.sentry.io/4505280648577024
```

2023-07-04 14:17 UTC, eswarasai commented on packages/app/src/config.ts
> +  VITE_SENTRY_DNS,
```suggestion
  VITE_SENTRY_DSN,
```

2023-07-04 14:17 UTC, eswarasai commented on packages/app/src/systems/Error/services/ReportErrorService.tsx
> +import { VITE_SENTRY_DNS } from '~/config';
```suggestion
import { VITE_SENTRY_DSN } from '~/config';
```

2023-07-04 14:17 UTC, eswarasai commented on packages/app/src/systems/Error/services/ReportErrorService.tsx
> +      dsn: VITE_SENTRY_DNS,
```suggestion
      dsn: VITE_SENTRY_DSN,
```

2023-07-04 17:26 UTC, eswarasai approved these changes
LGTM 👍

2023-07-04 18:06 UTC, LuizAsFight requested changes
small change

2023-07-05 11:16 UTC, eswarasai approved these changes
LGTM 👍

2023-07-06 04:26 UTC, LuizAsFight approved these changes

2023-07-06 04:26 UTC, merged