chore: remove xstore and storage and use fuels packs
FuelLabs/fuels-wallet pull request #857
Opened 2023-09-04 22:15 UTC by luizstacio

On this PR;
- Remove storage and xstate packages to use fuels-npm-packs.
- Use npm-fuels-packs

2023-09-06 00:26 UTC, LuizAsFight requested changes

2023-09-06 00:26 UTC, LuizAsFight commented on packages/app/package.json
> +    "@fuels/react-xstore": "0.0.7",
can we change all to `0.0.8` to get the machine fix ? (same applied in portal)

2023-09-06 15:15 UTC, pedronauck submitted a review, later dismissed

2023-09-06 19:03 UTC, luizstacio commented on packages/app/src/systems/Core/hooks/useStorage.tsx
> +    Storage.subscribe.bind(Storage),
Without it, the `Storage.subscribe` is called with the scope of the useSyncExternalStore

2023-09-06 21:41 UTC, luizstacio commented on packages/app/src/systems/Core/hooks/useStorage.tsx
> +    Storage.subscribe.bind(Storage),
@pedronauck https://github.com/FuelLabs/fuels-npm-packs/pull/18

2023-09-13 00:14 UTC, LuizAsFight approved these changes

2023-09-13 00:38 UTC, merged