refactor: test utils
FuelLabs/fuels-wallet pull request #960
Opened 2023-10-30 16:43 UTC by matt-user

closes #957

2023-11-01 02:10 UTC, luizstacio requested changes

2023-11-01 02:10 UTC, luizstacio commented on packages/docs/docs/dev/test-utils.mdx
> +title: Wallet Test Utils
I think would make sense to change for `Playwright Utils`

2023-11-01 02:10 UTC, luizstacio commented on packages/test-utils/package.json
>    "name": "@fuel-wallet/test-utils",
I think we should make the name `@fuel-wallet/playwright-utils`?

2023-11-02 02:11 UTC, LuizAsFight requested changes

2023-11-02 02:11 UTC, LuizAsFight commented on packages/e2e-contract-tests/playwright/e2e/DepositHalfEth.test.ts
> +      await fuelWalletTestHelper.getWalletNotificationPage();
would be better `getWalletPopupPage`?

```suggestion
    const walletPopupPage =
      await fuelWalletTestHelper.getWalletPopupPage();
```

2023-11-02 20:43 UTC, luizstacio approved these changes

2023-11-02 23:13 UTC, LuizAsFight approved these changes

2023-11-02 23:13 UTC, merged