refac(app): implement mediator/subscribe to avoid global states
FuelLabs/fuels-wallet pull request #97
Opened 2022-09-10 22:47 UTC by pedronauck

This pull request intends to implement a mediator/subscribe pattern in order to avoid global states and make it possible for us to communicate between our systems without creating a coupled system.

Alongside this implementation we get several benefits:

- Since the [service isn't started internally in React](https://github.com/FuelLabs/fuels-wallet/blob/refac/mediator/packages/app/src/systems/Core/utils/mediator/useMediator.tsx#L8-L14), you don’t need a provider, that’s a huge point!
```jsx
export function App() {
  return (
    <>
      <Counter />
      <Increment />
      <Decrement />
    </>
  )
}
```

- You can subscribe for an event in any component, and take action based on this event using a callback
- Systems don’t talk to each other, they talk with a mediator machine, and the mediator does the work. So, we don’t have coupled system in this way.

```jsx
useSubscribe(events.increment, (num) => {
  setCount((count) => count + num)
})
```

- All events are created as functions and can be in the scope of their on system, so if a system is deleted, is easy to map when we need to delete that event, since Typescript will complain that some event isn’t exist anymore

```jsx
// events.ts
import { createEvent } from "./mediator"

/**
 * Add a `{system}:` name before the event is a good way to don't have conflicts
 */
enum Events {
  increment = "counter:INCREMENT",
  decrement = "counter:DECREMENT",
}

export const increment = createEvent<number>(Events.increment)
export const decrement = createEvent<number>(Events.decrement)
```

- You can send an event from anywhere in code, you don’t need a hook or an internal react thing to dispatch to mediator
- All events are well-typed because they are functions created using a factory

```jsx
// component.ts
import * as events from "./events"

export function Increment() {
  return <button onClick={() => events.increment(2)}>Increment</button>
}
```

I really believe this is the better way to don't need a global provider that triggers a lot of re-renders and re-updates. This improves performance and our architecture since we can have scoped/more local states that don't know another part of the software.

2022-09-10 23:57 UTC, luizstacio requested changes

2022-09-10 23:57 UTC, luizstacio commented on packages/app/src/systems/Account/index.tsx
> +export { accountEvents };
`export * as accountEvents from "./events"`?

2022-09-11 03:05 UTC, pedronauck commented on packages/app/src/systems/Account/index.tsx
> +export { accountEvents };
✅

2022-09-11 19:41 UTC, luizstacio approved these changes

2022-09-11 19:41 UTC, merged