style: change text for creating new account in existing wallet
FuelLabs/fuels-wallet pull request #996
Opened 2023-12-05 22:23 UTC by richardgreg

Changed the text for "Add from private key" and "Add new account" to "Import from private key" and "Create new account."

close #992

2023-12-08 16:35 UTC, LuizAsFight requested changes

2023-12-08 16:35 UTC, LuizAsFight commented on packages/app/src/systems/Account/pages/Accounts/Accounts.tsx
> +          Create new account
can you keep this one as it was before?


the "import" change looks good

2023-12-13 03:32 UTC, luizstacio commented
This PR is missing the changesets. Can you add it by running: `pnpm changeset add --empty`

2024-01-10 20:25 UTC, luizstacio approved these changes

2024-01-10 21:17 UTC, merged